apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data-pvc
  labels:
    app: userapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rc-storage