apiVersion: v1
kind: Service
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8500
      name: userapi
  selector:
    app: userapi